terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
    azuread = {
      source  = "hashicorp/azuread"
      version = "~> 2.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.0"
    }
  }
}

provider "azurerm" {
  features {
    key_vault {
      purge_soft_delete_on_destroy = true
    }
  }
}

provider "azuread" {}

data "azurerm_client_config" "current" {}

# ============================================================
# Hardcoded suffix to match existing deployed resources.
# Originally generated by random_string but locked in once the
# resources were created. Treating it as a local removes the
# random_string state dependency.
# ============================================================
locals {
  suffix = "gvg8ly"
}

resource "azurerm_resource_group" "main" {
  name     = "rg-helpdesk-dev-${local.suffix}"
  location = var.location

  tags = {
    project     = "11-helpdesk-zero-touch"
    environment = "dev"
    managed_by  = "terraform"
    owner       = "MEEK"
  }
}
